//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfHwApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialAccounting
    {
        public int FinancialAccountingId { get; set; }
        public string Profit { get; set; }
        public string Costs { get; set; }
    }
}
